swagger: '2.0'
info:
  title: Azure Quantum Workspace Services Offerings SuiteOffers API
  version: 2026-01-15-preview
  description: Azure Quantum Workspace Services
  contact:
    email: azqengg@microsoft.com
  x-typespec-generated:
  - emitter: '@azure-tools/typespec-autorest'
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- AzureEntraAuth:
  - https://quantum.microsoft.com/.default
- AzureApiKeyAuth: []
tags:
- name: SuiteOffers
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Quantum/suiteOffers:
    get:
      operationId: SuiteOffers_ListBySubscription
      tags:
      - SuiteOffers
      description: Returns the SuiteOffer resource associated with the given name.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/QuantumSuiteOfferListResult'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        SuiteOffers_ListBySubscription:
          $ref: ./examples/SuiteOffers_ListBySubscription.json
      x-ms-pageable:
        nextLinkName: nextLink
definitions:
  QuantumSuiteOffer:
    type: object
    description: A Quantum Suite Offer that is available to a subscription.
    properties:
      properties:
        $ref: '#/definitions/QuantumSuiteOfferProperties'
        description: The resource-specific properties for this resource.
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource
  QuantumSuiteOfferProperties:
    type: object
    description: Properties of a Quantum Suite Offer
    properties:
      providerId:
        type: string
        description: The provider ID of the offer.
      providerName:
        type: string
        description: The provider name of the offer.
      companyName:
        type: string
        description: The name of the company that is providing this offer.
      location:
        type: string
        description: The location where this offer is available.
      description:
        type: string
        description: Description of the offer.
      quotas:
        $ref: '#/definitions/QuotaAllocations'
        description: Quota allocations associated with this offer.
    required:
    - providerId
    - providerName
    - companyName
    - location
    - description
  QuantumSuiteOfferListResult:
    type: object
    description: The response of a QuantumSuiteOffer list operation.
    properties:
      value:
        type: array
        description: The QuantumSuiteOffer items on this page
        items:
          $ref: '#/definitions/QuantumSuiteOffer'
      nextLink:
        type: string
        format: uri
        description: The link to the next page of items
    required:
    - value
  QuotaAllocations:
    type: object
    description: Quota allocations with each field representing different quota type.
    properties:
      standardMinutesLifetime:
        type: integer
        format: int32
        description: Lifetime limit for standard priority jobs execution in minutes.
        minimum: 0
      highMinutesLifetime:
        type: integer
        format: int32
        description: Lifetime limit for high priority jobs execution in minutes.
        minimum: 0
    required:
    - standardMinutesLifetime
securityDefinitions:
  AzureApiKeyAuth:
    type: apiKey
    description: Azure Api-Key Authentication
    name: x-ms-quantum-api-key
    in: header
  AzureEntraAuth:
    type: oauth2
    description: Azure Entra OAuth2 Authentication
    flow: application
    scopes:
      https://quantum.microsoft.com/.default: ''
    tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - name: endpoint
    in: path
    description: The endpoint of the Azure Quantum service. For example, https://{region}.quantum.azure.com
    required: true
    type: string
    format: uri
    x-ms-skip-url-encoding: true
